# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='new',
            name='media',
            field=models.ImageField(upload_to=''),
        ),
    ]
